import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/sidebar/sidebar";
import { MobileSidebar } from "@/components/sidebar/mobileSidebar";
import { Header } from "@/components/header";
import { ChatUI } from "@/components/chatUI";
import { InputForm } from "@/components/inputform";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="false"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row h-screen bg-gray-100">
          <SideBar />
          <MobileSidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
